### ISSUE TITLE
5.0版本安装后缺少eslint-config-standard所需依赖

### ISSUE THREAD

**Issue by jaredhan418** [vuejs/eslint-config-standard#2]
该版本使用peerDependencies依赖
eslint-plugin-standard 
eslint-plugin-promise 
eslint-plugin-import 
eslint-plugin-node
导致手动升级至5.0版本后需要手动安装这几个依赖，这是该插件开发时预期的行为吗？

**Comment by bruceCzK** [comment]
是这样的，参考这里 https://github.com/vuejs/eslint-config-standard/commit/75966d893d9dfa4359062896ade55545a673ffe7

这个修改之后其实这个仓库就没有存在的必要了，建议直接拿掉，自己手动安装那几个即可。

**Comment by greengiraffe** [comment]
Just as a hint for others who, like me, don't speak Chinese: this issue is a about the addition of a few eslint packages as peer dependencies, as introduced in version 5.0.0.

Here's a closed English language issue about the same topic: https://github.com/vuejs/eslint-config-standard/issues/1

Here's the discussion and reasoning for the change: https://github.com/vuejs/eslint-config-standard/commit/75966d893d9dfa4359062896ade55545a673ffe7#commitcomment-36004406
